knp_gaufrette:
  adapters:
    local_files:
      local:
        directory:  "%kernel.project_dir%/files/media"
        create:     true
  
  filesystems:
    cms_media:
      adapter: local_files
  
  stream_wrapper:
    filesystems:
      - cms_media
