knp_gaufrette:
  adapters:
    local_files:
      local:
        directory:  %root_directory%/files/media
        create:     true
  
  filesystems:
    cms_media:
      adapter: local_files
  
  stream_wrapper:
    filesystems:
      - cms_media
