liip_imagine:

  resolvers:
    default: 
      web_path:
        web_root: '%root_directory%/www'
        cache_prefix: /images/cache

  cache: webforge_meta_web_path

  # have a look at cms-services.yml for the definition of the wrapper in gaufrette
  loaders:
    cms_media_gaufrette:
      stream:
       wrapper: gaufrette://cms_media/

  data_loader: cms_media_gaufrette