services:
  # please not that the datetime handler is loaded from the dependency injection extension, because we cannot load from
  #imports:
  #  - { resource: '../../vendor/webforge/symfony/Resources/config/services.yml' }

  dc:
    class: Webforge\Doctrine\Entities
    arguments: ["@doctrine.orm.entity_manager", "%entities_namespace%"]

  webforge.liip_imagine.binary.loader.stream.cms_media:
    class: "%liip_imagine.binary.loader.stream.class%"
    arguments:
      - 'gaufrette://cms_media/'
    tags:
      - { name: 'liip_imagine.binary.loader', loader: 'stream.cms_media' }

  webforge.serialization.gaufrette_binary_handler:
    class:      Webforge\CmsBundle\Serialization\GaufretteBinaryHandler
    arguments: ['@knp_gaufrette.filesystem_map', 'cms_media', '@liip_imagine.cache.manager', '@liip_imagine.data.manager', '@liip_imagine.filter.manager', '@liip_imagine', '@liip_imagine.filter.configuration']
    tags: 
      - { name: jms_serializer.handler, direction: 'serialization', format: 'json', type: 'WebforgeGaufretteBinary', method: 'serialize' }
#    tags: 
#      - { name: jms_serializer.event_listener, event: serializer.post_serialize, class: WebforgeGaufretteBinary }

  webforge.serialization.special_types_listener:
    class:      Webforge\CmsBundle\Serialization\SpecialTypesListener
    arguments:
      - { Webforge\CmsBundle\Model\GaufretteFileInterface: WebforgeGaufretteBinary }
    tags: 
      - { name: jms_serializer.event_listener, event: serializer.pre_serialize }

  webforge.imagine.meta_web_path_resolver:
    class: Webforge\CmsBundle\Imagine\MetaWebPathResolver
    arguments: ['@liip_imagine.cache.resolver.default']
    calls:
      - [setImagine, ['@liip_imagine']]
    tags:
      - { name: 'liip_imagine.cache.resolver', resolver: 'webforge_meta_web_path' }
  
  webforge.cache.imagine_cache_warmer:
    class: Webforge\CmsBundle\Cache\ImagineCacheWarmer
    arguments: ['@webforge.serialization.gaufrette_binary_handler']
    tags:
      - { name: kernel.cache_warmer, priority: 1 }

  webforge.media.persistent_storage:
    class: Webforge\CmsBundle\Media\PersistentStorage
    arguments: ['@dc', 'Binary']