parameters:
  webforge_media_filesystem_domain: 'cms_media'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  dc:
    class: Webforge\Doctrine\Entities
    arguments: ["@doctrine.orm.entity_manager", "%entities_namespace%"]

  webforge.serialization.jms_serializer_media_file_entity_handler:
    class:      Webforge\CmsBundle\Serialization\JmsSerializerMediaFileEntityHandler
    arguments: ['@webforge.media.manager']
    tags: 
      - { name: jms_serializer.handler, direction: 'serialization', format: 'json', type: 'WebforgeMediaFileEntity', method: 'serialize' }

  webforge.serialization.special_types_listener:
    class:      Webforge\CmsBundle\Serialization\SpecialTypesListener
    arguments:
      - { Webforge\CmsBundle\Model\MediaFileEntityInterface: WebforgeMediaFileEntity }
    tags: 
      - { name: jms_serializer.event_listener, event: serializer.pre_serialize }

  webforge.serialization.thumbor_thumbnails_file_handler:
    class: Webforge\CmsBundle\Serialization\ThumborThumbnailsFileHandler
    arguments:
      - '%phumbor.transformations%'
      - '@phumbor.url.transformer'
      - '@logger'
    calls:
      - ["setManager", ['@webforge.media.manager']]


  webforge.cache.images_cache_warmer:
    class: Webforge\CmsBundle\Cache\ImagesCacheWarmer
    arguments: ['@webforge.media.manager']
    tags:
      - { name: kernel.cache_warmer, priority: 1 }

  webforge.media.persistent_storage:
    class: Webforge\CmsBundle\Media\PersistentStorage
    arguments: ['@dc', 'Binary', 'MediaTree']

  webforge.media.filesystem:
    class: Gaufrette\Filesystem
    factory: 'knp_gaufrette.filesystem_map:get'
    arguments: ['%webforge_media_filesystem_domain%']

  webforge.gaufrette_index:
    class: Webforge\Gaufrette\Index
    arguments: ['@webforge.media.filesystem']

  webforge.media.manager:
    class: Webforge\CmsBundle\Media\Manager
    arguments: 
      - '@webforge.media.filesystem'
      - '@webforge.gaufrette_index'
      - '@webforge.media.persistent_storage'
      - ['@webforge.serialization.thumbor_thumbnails_file_handler']
      - '@router'
      - '%knp_gaufrette.stream_wrapper.protocol%'
      - '%webforge_media_filesystem_domain%'

  webforge.content.common_block_extender:
    class: Webforge\CmsBundle\Content\CommonBlockExtender
    arguments: ["@markdowner", "@webforge.media.manager"]
    tags:
      - { name: webforge_cms.content.block_extender, priority: 50 } #(the highest the priority, the earlier a listener is executed)

  webforge.content.blocks:
    class: Webforge\CmsBundle\Content\Blocks
    arguments: [ [], "%kernel.project_dir%/etc/cms/blocktypes.json", "@markdowner" ]  #first argument will be written with compiler pass

  markdowner:
    class: Webforge\CmsBundle\Content\Markdowner
    arguments: ["@markdown.parser"]

  webforge_symfony_datetimehandler:
    class:      Webforge\Symfony\DateTimeHandler
    arguments: []
    tags:
      - { name: jms_serializer.subscribing_handler }
      - { name: nelmio_alice.faker.provider }

  webforge_symfony_form_iso_8601_date_time_type:
    class: Webforge\Symfony\Form\Iso8601DateTimeType
    tags:
      - { name: form.type, alias: webforge_iso8601_date_time }

  webforge_symfony_dql_query_command:
    class: Webforge\Symfony\Commands\DqlQueryCommand
    arguments: ["@doctrine"]
    tags:
      -  { name: console.command }

  webforge_mail_spool_command:
    class: Webforge\CmsBundle\Command\MailSpoolCommand
    tags:
      -  { name: console.command }

  webforge_warmup_media_file_command:
    class: \Webforge\CmsBundle\Command\WarmupMediaFileMetaCommand
    tags:
      -  { name: console.command }
