services:
    # hook the datetime handler into jms serializer to convert through frontend and backend
    datetimehandler:
      class:      Webforge\CmsBundle\DateTimeHandler
      arguments: []
      tags: 
        - { name: jms_serializer.subscribing_handler }
