parameters:
  webforge_media_filesystem_domain: 'cms_media'

services:
  # please not that the datetime handler is loaded from the dependency injection extension, because we cannot load from
  #imports:
  #  - { resource: '../../vendor/webforge/symfony/Resources/config/services.yml' }

  dc:
    class: Webforge\Doctrine\Entities
    arguments: ["@doctrine.orm.entity_manager", "%entities_namespace%"]

  webforge.liip_imagine.binary.loader.stream.cms_media:
    class: "%liip_imagine.binary.loader.stream.class%"
    arguments:
      - 'gaufrette://cms_media/'
    tags:
      - { name: 'liip_imagine.binary.loader', loader: 'stream.cms_media' }

  webforge.serialization.jms_serializer_media_file_entity_handler:
    class:      Webforge\CmsBundle\Serialization\JmsSerializerMediaFileEntityHandler
    arguments: ['@webforge.media.manager']
    tags: 
      - { name: jms_serializer.handler, direction: 'serialization', format: 'json', type: 'WebforgeMediaFileEntity', method: 'serialize' }
      - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: 'onPostSerialize' }

  webforge.serialization.special_types_listener:
    class:      Webforge\CmsBundle\Serialization\SpecialTypesListener
    arguments:
      - { Webforge\CmsBundle\Model\MediaFileEntityInterface: WebforgeMediaFileEntity }
    tags: 
      - { name: jms_serializer.event_listener, event: serializer.pre_serialize }

  webforge.serialization.imagine_thumbnails_file_handler:
    class: Webforge\CmsBundle\Serialization\ImagineThumbnailsFileHandler
    arguments: ['@liip_imagine.cache.manager', '@liip_imagine.data.manager', '@liip_imagine.filter.manager', '@liip_imagine', '@liip_imagine.filter.configuration', '@webforge.imagine.meta_web_path_resolver', '@webforge.imagine.meta_cache']

  webforge.serialization.thumbor_thumbnails_file_handler:
    class: Webforge\CmsBundle\Serialization\ThumborThumbnailsFileHandler
    arguments:
      - '%phumbor.transformations%'
      - '@phumbor.url.transformer'
      - '@webforge.media.filesystem'

  webforge.imagine.meta_cache:
    class: Doctrine\Common\Cache\ChainCache
    factory: ['Webforge\CmsBundle\Imagine\MetaWebPathResolver', 'createCache']

  webforge.imagine.meta_web_path_resolver:
    class: Webforge\CmsBundle\Imagine\MetaWebPathResolver
    arguments: ['@liip_imagine.cache.resolver.default', '@webforge.imagine.meta_cache']
    calls:
      - [setImagine, ['@liip_imagine']]
    tags:
      - { name: 'liip_imagine.cache.resolver', resolver: 'webforge_meta_web_path' }
  
  webforge.cache.imagine_cache_warmer:
    class: Webforge\CmsBundle\Cache\ImagineCacheWarmer
    arguments: ['@webforge.media.manager']
    tags:
      - { name: kernel.cache_warmer, priority: 1 }

  webforge.media.persistent_storage:
    class: Webforge\CmsBundle\Media\PersistentStorage
    arguments: ['@dc', 'Binary', 'MediaTree']

  webforge.media.filesystem:
    class: Gaufrette\Filesystem
    factory: 'knp_gaufrette.filesystem_map:get'
    arguments: ['%webforge_media_filesystem_domain%']

  webforge.gaufrette_index:
    class: Webforge\Gaufrette\Index
    arguments: ['@webforge.media.filesystem']

  webforge.media.manager:
    class: Webforge\CmsBundle\Media\Manager
    arguments: 
      - '@webforge.media.filesystem'
      - '@webforge.gaufrette_index'
      - '@webforge.media.persistent_storage'
      - ['@webforge.serialization.imagine_thumbnails_file_handler', '@webforge.serialization.thumbor_thumbnails_file_handler']
      - '@router'
      - '%knp_gaufrette.stream_wrapper.protocol%'
      - '%webforge_media_filesystem_domain%'

  webforge.media.alice_fixtures_provider:
    class: Webforge\CmsBundle\Media\AliceFixturesProvider
    arguments: ['@webforge.media.manager']
    tags: 
      - { name: webforge_cms.alice_fixtures_provider }
  
  webforge.content.common_block_extender:
    class: Webforge\CmsBundle\Content\CommonBlockExtender
    arguments: ["@markdowner", "@webforge.media.manager"]
    tags:
      - { name: webforge_cms.content.block_extender, priority: 50 } #(the highest the priority, the earlier a listener is executed)

  webforge.content.blocks:
    class: Webforge\CmsBundle\Content\Blocks
    arguments: [ [], "%root_directory%/etc/cms/blocktypes.json", "@markdowner" ]  #first argument will be written with compiler pass

  markdowner:
    class: Webforge\CmsBundle\Content\Markdowner
    arguments: ["@markdown.parser"]
