services:
    # please not that the datetime handler is loaded from the dependency injection extension, because we cannot load from
    #imports:
    #  - { resource: '../../vendor/webforge/symfony/Resources/config/services.yml' }
