imports:
    - { resource: ./parts/framework.yml }
    - { resource: ./parts/security.yml }
    - { resource: ./parts/doctrine.yml }
    - { resource: ./parts/fos_user.yml }
    - { resource: ./parts/serializer.yml }
    - { resource: ./parts/twig.yml }
    - { resource: ./parts/swiftmailer.yml }
    - { resource: ./parts/gaufrette.yml }

parameters:
  mailer_spoolpath: "%kernel.project_dir%/files/mailspool"
