imports:
    - { resource: config.yml }

services:
#    now: 
#        class: "Webforge\\Common\\DateTime\\DateTime"
#        arguments: ['08.10.2015 10:11']

framework:
    router:
        resource: "%root_directory%/etc/symfony/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    delivery_address: 'p.scheit@ps-webforge.com'
    spool:
        type: file
        path: "%mailer_spoolpath%"
