imports:
    - { resource: config.yml }

services:
#    now: 
#        class: "Webforge\\Common\\DateTime\\DateTime"
#        arguments: ['08.10.2015 10:11']

framework:
    router:
        resource: "%root_directory%/etc/symfony/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    delivery_address: p.scheit@ps-webforge.com

h4cc_alice_fixtures:
    locale: de_De                               # default
    seed: 7                                     # default
    do_flush: true                              # default

    schema_tool: null                           # default
    doctrine: orm