imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.project_dir%/etc/symfony/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    delivery_address: 'p.scheit@ps-webforge.com'
    spool:
        type: file
        path: "%mailer_spoolpath%"
