imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: parts/monolog.yml }
    - { resource: parts/images.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    entities_namespace: 'AppBundle\Entity'
    secret: 9w349sdfDFLKJ2349dsf90i
    locale: de
    router.request_context.host: "%env(DOMAIN)%"
    version: "%env(BUILD_VERSION)%"
    mail_from: 'info@ps-webforge.com'
    mail_from_name: 'Webforge'

jb_phumbor:
    server:
        url: "%thumbor_server%"
        secret: "%thumbor_secret%"