imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: parts/monolog.yml }
    - { resource: parts/images.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de


# overwride the non-mapping-for-WebforgeCmsBundle part for other projects
# this project uses the extended entities itself
doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true

                mappings:
                    WebforgeCmsBundle:
                        mapping:              true
                        type:                 annotation
                        dir:                  ~
                        alias:                ~
                        prefix:               Webforge\CmsBundle\Entity
                        is_bundle:            true