imports:
    - { resource: config.yml }

parameters:
    # we cannot link directly (in the network) to thumbor, because the browser on host uses this hostname to connect to the image server (not the docker container itself, but sometimes)
    thumbor_server: 'http://docker-host:8000'
    thumbor_secret: gJ5n38f7o0TilkkmMTEB

framework:
    router:
        resource: "%kernel.project_dir%/etc/symfony/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    delivery_address: 'p.scheit@ps-webforge.com'
    spool:
        type: file
        path: "%mailer_spoolpath%"
