imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

services:
    now: 
        class: "Webforge\\Common\\DateTime\\DateTime"
        arguments: ['08.10.2015 10:11']
