imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: parts/monolog.yml }
    - { resource: parts/images.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
