home:
  path: /
  defaults:
      _controller: FrameworkBundle:Redirect:urlRedirect
      path: /cms
      permanent: true  

cms:
    resource: "@WebforgeCmsBundle/Controller"
    prefix: /cms
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"