# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    entities_namespace: 'AppBundle\Entity'

services:
    now: 
        class: "Webforge\\Common\\DateTime\\DateTime"
        factory_class: "Webforge\\Common\\DateTime\\DateTime"
        factory_method: now
