# these services are only used to run the cms-appbundle and they are not global
services:
    now: 
        class: "Webforge\\Common\\DateTime\\DateTime"
        factory: ["Webforge\\Common\\DateTime\\DateTime", "now"]

    globals_twig_extension:
        class: AppBundle\Twig\GlobalVariablesExtension
        arguments: []
        tags:
            - { name: twig.extension }
