language: node_js

sudo: false

node_js:
  - "6"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm run build-dev

notifications:
  slack: webforge:4FtiiZn6TyN29SI8ESWDqUAa