language: node_js

sudo: false

node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm run build-dev

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@239240
