version: "3.0"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

services:

  web:
    image: nginx:1.13-alpine

    ports:
      - "${NGINX_PORT}:80"

    volumes:
      - ./etc/docker/symfony.inc:/etc/nginx/symfony.inc:ro
      - ./etc/docker/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - php
    
  php:
    image: webforgecms/php:latest
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile

    volumes:
      - appcache:/app/files/cache
      - ./etc/docker/fpm-pool.conf:/usr/local/etc/php-fpm.d/z-www.conf

    extra_hosts:
      - "docker-host:${DOCKER_HOSTIP}"

    # these are passed through from .env file (or other passed in variables)
    environment:
      - SYMFONY_ENV
      - SYMFONY_DEBUG
      - SYMFONY_BASEURL
      - SYMFONY__ROUTER__REQUEST_CONTEXT__HOST
      - SYMFONY__BUILD_VERSION

volumes:
  # we just need write support (www-data) for php-fpm on this dir. We might discard this volume with docker-compose down -v (to start with no symfony-cache)
  # note that imagine-meta will be host-binded above this cache dir
  appcache:
